name: smart_attendance
description: BLE + Face Recognition attendance mobile app.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BLE scanning for classroom beacon detection
  flutter_blue_plus: ^1.35.2

  # Camera capture (front-facing selfie)
  # HTTP client for FastAPI backend communication
  http: ^1.2.2

  # Runtime permission requests (Bluetooth, Camera, Location)
  permission_handler: ^11.3.1

  # Temp directory access for captured images
  path_provider: ^2.1.4

  # Local push notifications
  flutter_local_notifications: ^18.0.1

  # Background execution service
  flutter_background_service: ^5.0.12
  flutter_background_service_android: ^6.2.8

  # Local persistence for student profile & server settings
  shared_preferences: ^2.3.2

  # Material Design icons (included with Flutter SDK)
  cupertino_icons: ^1.0.8
  camera: ^0.12.1
  google_mlkit_face_detection: ^0.15.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
